---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gatus.io
  resources:
  - announcements
  - endpoints
  - externalendpoints
  - instances
  - suites
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gatus.io
  resources:
  - announcements/finalizers
  - endpoints/finalizers
  - externalendpoints/finalizers
  - instances/finalizers
  - suites/finalizers
  verbs:
  - update
- apiGroups:
  - gatus.io
  resources:
  - announcements/status
  - endpoints/status
  - externalendpoints/status
  - instances/status
  - suites/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
