apiVersion: gatus.io/v1alpha1
kind: Endpoint
metadata:
  labels:
    app.kubernetes.io/name: projects
    app.kubernetes.io/managed-by: kustomize
  name: endpoint-sample
spec:
  instances:
    - name: instance-sample
      namespace: default
  config:
    name: Test
    url: http://test-service
    conditions:
      - "[STATUS] == 200"
