apiVersion: gatus.io/v1alpha1
kind: Instance
metadata:
  labels:
    app.kubernetes.io/name: projects
    app.kubernetes.io/managed-by: kustomize
  name: instance-sample
spec:
  name: "Test-Gatus"
  image: "ghcr.io/twin/gatus:stable"
