apiVersion: gatus.io/v1alpha1
kind: Instance
metadata:
  labels:
    app.kubernetes.io/name: projects
    app.kubernetes.io/managed-by: kustomize
  name: instance-sample
spec:
  name: "Test-Gatus"
  # image: "ghcr.io/twin/gatus:stable"
  service:
    enable: true
    ipFamilyPolicy: "PreferDualStack"
    # ipFamilies:
    #   - "IPv4"
    #   - "IPv6"
  gatus-config:
    # metrics:
    # alerting:
    #   discord:
    #     webhook-url: ""
    # concurrency:
    # connectivity:
    # storage:
    # security:
    # web:
    ui:
      header: "My Status Page"
    # maintenance:
