apiVersion: gatus.io/v1alpha1
kind: Announcement
metadata:
  labels:
    app.kubernetes.io/name: projects
    app.kubernetes.io/managed-by: kustomize
  name: announcement-sample
spec:
  # TODO(user): Add fields here
