//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	gatus_config "github.com/Jannik-Hm/Gatus-Operator/internal/gatus_config"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Announcement) DeepCopyInto(out *Announcement) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Announcement.
func (in *Announcement) DeepCopy() *Announcement {
	if in == nil {
		return nil
	}
	out := new(Announcement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Announcement) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnouncementConfigSpec) DeepCopyInto(out *AnnouncementConfigSpec) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.Archived != nil {
		in, out := &in.Archived, &out.Archived
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnouncementConfigSpec.
func (in *AnnouncementConfigSpec) DeepCopy() *AnnouncementConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AnnouncementConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnouncementList) DeepCopyInto(out *AnnouncementList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Announcement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnouncementList.
func (in *AnnouncementList) DeepCopy() *AnnouncementList {
	if in == nil {
		return nil
	}
	out := new(AnnouncementList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnnouncementList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnouncementSpec) DeepCopyInto(out *AnnouncementSpec) {
	*out = *in
	in.InstanceReference.DeepCopyInto(&out.InstanceReference)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnouncementSpec.
func (in *AnnouncementSpec) DeepCopy() *AnnouncementSpec {
	if in == nil {
		return nil
	}
	out := new(AnnouncementSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnnouncementStatus) DeepCopyInto(out *AnnouncementStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnnouncementStatus.
func (in *AnnouncementStatus) DeepCopy() *AnnouncementStatus {
	if in == nil {
		return nil
	}
	out := new(AnnouncementStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint.
func (in *Endpoint) DeepCopy() *Endpoint {
	if in == nil {
		return nil
	}
	out := new(Endpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Endpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointAlertSpec) DeepCopyInto(out *EndpointAlertSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.FailureThreshold != nil {
		in, out := &in.FailureThreshold, &out.FailureThreshold
		*out = new(int32)
		**out = **in
	}
	if in.SuccessThreshold != nil {
		in, out := &in.SuccessThreshold, &out.SuccessThreshold
		*out = new(int32)
		**out = **in
	}
	if in.MinimumReminderInterval != nil {
		in, out := &in.MinimumReminderInterval, &out.MinimumReminderInterval
		*out = new(string)
		**out = **in
	}
	if in.SendOnResolved != nil {
		in, out := &in.SendOnResolved, &out.SendOnResolved
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ProviderOverride != nil {
		in, out := &in.ProviderOverride, &out.ProviderOverride
		*out = make(map[string]runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointAlertSpec.
func (in *EndpointAlertSpec) DeepCopy() *EndpointAlertSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointAlertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointClientIdentityAwareProxySpec) DeepCopyInto(out *EndpointClientIdentityAwareProxySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointClientIdentityAwareProxySpec.
func (in *EndpointClientIdentityAwareProxySpec) DeepCopy() *EndpointClientIdentityAwareProxySpec {
	if in == nil {
		return nil
	}
	out := new(EndpointClientIdentityAwareProxySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointClientOauth2Spec) DeepCopyInto(out *EndpointClientOauth2Spec) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointClientOauth2Spec.
func (in *EndpointClientOauth2Spec) DeepCopy() *EndpointClientOauth2Spec {
	if in == nil {
		return nil
	}
	out := new(EndpointClientOauth2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointClientSpec) DeepCopyInto(out *EndpointClientSpec) {
	*out = *in
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreRedirect != nil {
		in, out := &in.IgnoreRedirect, &out.IgnoreRedirect
		*out = new(bool)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.DNSResolver != nil {
		in, out := &in.DNSResolver, &out.DNSResolver
		*out = new(string)
		**out = **in
	}
	if in.Oauth2 != nil {
		in, out := &in.Oauth2, &out.Oauth2
		*out = new(EndpointClientOauth2Spec)
		(*in).DeepCopyInto(*out)
	}
	if in.ProxyURL != nil {
		in, out := &in.ProxyURL, &out.ProxyURL
		*out = new(string)
		**out = **in
	}
	if in.IdentityAwareProxy != nil {
		in, out := &in.IdentityAwareProxy, &out.IdentityAwareProxy
		*out = new(EndpointClientIdentityAwareProxySpec)
		**out = **in
	}
	if in.MTLS != nil {
		in, out := &in.MTLS, &out.MTLS
		*out = new(EndpointClientmTLSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointClientSpec.
func (in *EndpointClientSpec) DeepCopy() *EndpointClientSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointClientmTLSSpec) DeepCopyInto(out *EndpointClientmTLSSpec) {
	*out = *in
	if in.CertificateFile != nil {
		in, out := &in.CertificateFile, &out.CertificateFile
		*out = new(string)
		**out = **in
	}
	if in.PrivateKeyFile != nil {
		in, out := &in.PrivateKeyFile, &out.PrivateKeyFile
		*out = new(string)
		**out = **in
	}
	if in.Renegotiation != nil {
		in, out := &in.Renegotiation, &out.Renegotiation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointClientmTLSSpec.
func (in *EndpointClientmTLSSpec) DeepCopy() *EndpointClientmTLSSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointClientmTLSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointConfigSpec) DeepCopyInto(out *EndpointConfigSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
	if in.GraphQL != nil {
		in, out := &in.GraphQL, &out.GraphQL
		*out = new(bool)
		**out = **in
	}
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(string)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(EndpointDNSSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SSH != nil {
		in, out := &in.SSH, &out.SSH
		*out = new(EndpointSSHSpec)
		**out = **in
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]*EndpointAlertSpec, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(EndpointAlertSpec)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.MaintenanceWindows != nil {
		in, out := &in.MaintenanceWindows, &out.MaintenanceWindows
		*out = make([]*GatusMaintenanceSpec, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(GatusMaintenanceSpec)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(EndpointClientSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Ui != nil {
		in, out := &in.Ui, &out.Ui
		*out = new(EndpointUiSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraLabels != nil {
		in, out := &in.ExtraLabels, &out.ExtraLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointConfigSpec.
func (in *EndpointConfigSpec) DeepCopy() *EndpointConfigSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointDNSSpec) DeepCopyInto(out *EndpointDNSSpec) {
	*out = *in
	if in.QueryType != nil {
		in, out := &in.QueryType, &out.QueryType
		*out = new(string)
		**out = **in
	}
	if in.QueryName != nil {
		in, out := &in.QueryName, &out.QueryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointDNSSpec.
func (in *EndpointDNSSpec) DeepCopy() *EndpointDNSSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointDNSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointList) DeepCopyInto(out *EndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Endpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointList.
func (in *EndpointList) DeepCopy() *EndpointList {
	if in == nil {
		return nil
	}
	out := new(EndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSSHSpec) DeepCopyInto(out *EndpointSSHSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSSHSpec.
func (in *EndpointSSHSpec) DeepCopy() *EndpointSSHSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointSSHSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointSpec) DeepCopyInto(out *EndpointSpec) {
	*out = *in
	in.InstanceReference.DeepCopyInto(&out.InstanceReference)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointSpec.
func (in *EndpointSpec) DeepCopy() *EndpointSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointStatus) DeepCopyInto(out *EndpointStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointStatus.
func (in *EndpointStatus) DeepCopy() *EndpointStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointUiBadgeResponseTimeSpec) DeepCopyInto(out *EndpointUiBadgeResponseTimeSpec) {
	*out = *in
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointUiBadgeResponseTimeSpec.
func (in *EndpointUiBadgeResponseTimeSpec) DeepCopy() *EndpointUiBadgeResponseTimeSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointUiBadgeResponseTimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointUiBadgeSpec) DeepCopyInto(out *EndpointUiBadgeSpec) {
	*out = *in
	if in.ResponseTime != nil {
		in, out := &in.ResponseTime, &out.ResponseTime
		*out = new(EndpointUiBadgeResponseTimeSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointUiBadgeSpec.
func (in *EndpointUiBadgeSpec) DeepCopy() *EndpointUiBadgeSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointUiBadgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointUiSpec) DeepCopyInto(out *EndpointUiSpec) {
	*out = *in
	if in.HideConditions != nil {
		in, out := &in.HideConditions, &out.HideConditions
		*out = new(bool)
		**out = **in
	}
	if in.HideHostname != nil {
		in, out := &in.HideHostname, &out.HideHostname
		*out = new(bool)
		**out = **in
	}
	if in.HidePort != nil {
		in, out := &in.HidePort, &out.HidePort
		*out = new(bool)
		**out = **in
	}
	if in.HideUrl != nil {
		in, out := &in.HideUrl, &out.HideUrl
		*out = new(bool)
		**out = **in
	}
	if in.HideErrors != nil {
		in, out := &in.HideErrors, &out.HideErrors
		*out = new(bool)
		**out = **in
	}
	if in.DontResolveFailedConditions != nil {
		in, out := &in.DontResolveFailedConditions, &out.DontResolveFailedConditions
		*out = new(bool)
		**out = **in
	}
	if in.ResolveSuccessfulConditions != nil {
		in, out := &in.ResolveSuccessfulConditions, &out.ResolveSuccessfulConditions
		*out = new(bool)
		**out = **in
	}
	if in.Badge != nil {
		in, out := &in.Badge, &out.Badge
		*out = new(EndpointUiBadgeSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointUiSpec.
func (in *EndpointUiSpec) DeepCopy() *EndpointUiSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointUiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalEndpoint) DeepCopyInto(out *ExternalEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalEndpoint.
func (in *ExternalEndpoint) DeepCopy() *ExternalEndpoint {
	if in == nil {
		return nil
	}
	out := new(ExternalEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalEndpointConfigSpec) DeepCopyInto(out *ExternalEndpointConfigSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]*EndpointAlertSpec, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(EndpointAlertSpec)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	in.Heartbeat.DeepCopyInto(&out.Heartbeat)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalEndpointConfigSpec.
func (in *ExternalEndpointConfigSpec) DeepCopy() *ExternalEndpointConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalEndpointConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalEndpointHeartbeatSpec) DeepCopyInto(out *ExternalEndpointHeartbeatSpec) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalEndpointHeartbeatSpec.
func (in *ExternalEndpointHeartbeatSpec) DeepCopy() *ExternalEndpointHeartbeatSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalEndpointHeartbeatSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalEndpointList) DeepCopyInto(out *ExternalEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExternalEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalEndpointList.
func (in *ExternalEndpointList) DeepCopy() *ExternalEndpointList {
	if in == nil {
		return nil
	}
	out := new(ExternalEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExternalEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalEndpointSpec) DeepCopyInto(out *ExternalEndpointSpec) {
	*out = *in
	in.InstanceReference.DeepCopyInto(&out.InstanceReference)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalEndpointSpec.
func (in *ExternalEndpointSpec) DeepCopy() *ExternalEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalEndpointStatus) DeepCopyInto(out *ExternalEndpointStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalEndpointStatus.
func (in *ExternalEndpointStatus) DeepCopy() *ExternalEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusConnectivityCheckerSpec) DeepCopyInto(out *GatusConnectivityCheckerSpec) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusConnectivityCheckerSpec.
func (in *GatusConnectivityCheckerSpec) DeepCopy() *GatusConnectivityCheckerSpec {
	if in == nil {
		return nil
	}
	out := new(GatusConnectivityCheckerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusConnectivitySpec) DeepCopyInto(out *GatusConnectivitySpec) {
	*out = *in
	in.Checker.DeepCopyInto(&out.Checker)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusConnectivitySpec.
func (in *GatusConnectivitySpec) DeepCopy() *GatusConnectivitySpec {
	if in == nil {
		return nil
	}
	out := new(GatusConnectivitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusInstanceSpec) DeepCopyInto(out *GatusInstanceSpec) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(bool)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(GatusStorageSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Alerting != nil {
		in, out := &in.Alerting, &out.Alerting
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(GatusSecuritySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(int32)
		**out = **in
	}
	if in.Web != nil {
		in, out := &in.Web, &out.Web
		*out = new(GatusInstanceWebSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Ui != nil {
		in, out := &in.Ui, &out.Ui
		*out = new(GatusUiSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Maintenance != nil {
		in, out := &in.Maintenance, &out.Maintenance
		*out = new(GatusMaintenanceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Connectivity != nil {
		in, out := &in.Connectivity, &out.Connectivity
		*out = new(GatusConnectivitySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusInstanceSpec.
func (in *GatusInstanceSpec) DeepCopy() *GatusInstanceSpec {
	if in == nil {
		return nil
	}
	out := new(GatusInstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusInstanceWebSpec) DeepCopyInto(out *GatusInstanceWebSpec) {
	*out = *in
	if in.ReadBufferSize != nil {
		in, out := &in.ReadBufferSize, &out.ReadBufferSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusInstanceWebSpec.
func (in *GatusInstanceWebSpec) DeepCopy() *GatusInstanceWebSpec {
	if in == nil {
		return nil
	}
	out := new(GatusInstanceWebSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusMaintenanceSpec) DeepCopyInto(out *GatusMaintenanceSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Timezone != nil {
		in, out := &in.Timezone, &out.Timezone
		*out = new(string)
		**out = **in
	}
	if in.Every != nil {
		in, out := &in.Every, &out.Every
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusMaintenanceSpec.
func (in *GatusMaintenanceSpec) DeepCopy() *GatusMaintenanceSpec {
	if in == nil {
		return nil
	}
	out := new(GatusMaintenanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusSecurityBasicSpec) DeepCopyInto(out *GatusSecurityBasicSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusSecurityBasicSpec.
func (in *GatusSecurityBasicSpec) DeepCopy() *GatusSecurityBasicSpec {
	if in == nil {
		return nil
	}
	out := new(GatusSecurityBasicSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusSecurityOIDCSpec) DeepCopyInto(out *GatusSecurityOIDCSpec) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedSubjects != nil {
		in, out := &in.AllowedSubjects, &out.AllowedSubjects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SessionTTL != nil {
		in, out := &in.SessionTTL, &out.SessionTTL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusSecurityOIDCSpec.
func (in *GatusSecurityOIDCSpec) DeepCopy() *GatusSecurityOIDCSpec {
	if in == nil {
		return nil
	}
	out := new(GatusSecurityOIDCSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusSecuritySpec) DeepCopyInto(out *GatusSecuritySpec) {
	*out = *in
	if in.Basic != nil {
		in, out := &in.Basic, &out.Basic
		*out = new(GatusSecurityBasicSpec)
		**out = **in
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(GatusSecurityOIDCSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusSecuritySpec.
func (in *GatusSecuritySpec) DeepCopy() *GatusSecuritySpec {
	if in == nil {
		return nil
	}
	out := new(GatusSecuritySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusStorageSpec) DeepCopyInto(out *GatusStorageSpec) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(gatus_config.GatusStorageType)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Caching != nil {
		in, out := &in.Caching, &out.Caching
		*out = new(bool)
		**out = **in
	}
	if in.MaximumResultsNum != nil {
		in, out := &in.MaximumResultsNum, &out.MaximumResultsNum
		*out = new(int32)
		**out = **in
	}
	if in.MaximumEventsNum != nil {
		in, out := &in.MaximumEventsNum, &out.MaximumEventsNum
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusStorageSpec.
func (in *GatusStorageSpec) DeepCopy() *GatusStorageSpec {
	if in == nil {
		return nil
	}
	out := new(GatusStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusUiButtonSpec) DeepCopyInto(out *GatusUiButtonSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusUiButtonSpec.
func (in *GatusUiButtonSpec) DeepCopy() *GatusUiButtonSpec {
	if in == nil {
		return nil
	}
	out := new(GatusUiButtonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusUiFaviconSpec) DeepCopyInto(out *GatusUiFaviconSpec) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Size16x16 != nil {
		in, out := &in.Size16x16, &out.Size16x16
		*out = new(string)
		**out = **in
	}
	if in.Size32x32 != nil {
		in, out := &in.Size32x32, &out.Size32x32
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusUiFaviconSpec.
func (in *GatusUiFaviconSpec) DeepCopy() *GatusUiFaviconSpec {
	if in == nil {
		return nil
	}
	out := new(GatusUiFaviconSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusUiSpec) DeepCopyInto(out *GatusUiSpec) {
	*out = *in
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DashboardHeading != nil {
		in, out := &in.DashboardHeading, &out.DashboardHeading
		*out = new(string)
		**out = **in
	}
	if in.DashboardSubheading != nil {
		in, out := &in.DashboardSubheading, &out.DashboardSubheading
		*out = new(string)
		**out = **in
	}
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(string)
		**out = **in
	}
	if in.Logo != nil {
		in, out := &in.Logo, &out.Logo
		*out = new(string)
		**out = **in
	}
	if in.Link != nil {
		in, out := &in.Link, &out.Link
		*out = new(string)
		**out = **in
	}
	if in.Favicon != nil {
		in, out := &in.Favicon, &out.Favicon
		*out = new(GatusUiFaviconSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Buttons != nil {
		in, out := &in.Buttons, &out.Buttons
		*out = make([]*GatusUiButtonSpec, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(GatusUiButtonSpec)
				**out = **in
			}
		}
	}
	if in.CustomCSS != nil {
		in, out := &in.CustomCSS, &out.CustomCSS
		*out = new(string)
		**out = **in
	}
	if in.Darkmode != nil {
		in, out := &in.Darkmode, &out.Darkmode
		*out = new(bool)
		**out = **in
	}
	if in.DefaultSortBy != nil {
		in, out := &in.DefaultSortBy, &out.DefaultSortBy
		*out = new(string)
		**out = **in
	}
	if in.DefaultFilterBy != nil {
		in, out := &in.DefaultFilterBy, &out.DefaultFilterBy
		*out = new(string)
		**out = **in
	}
	if in.LoginSubtitle != nil {
		in, out := &in.LoginSubtitle, &out.LoginSubtitle
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusUiSpec.
func (in *GatusUiSpec) DeepCopy() *GatusUiSpec {
	if in == nil {
		return nil
	}
	out := new(GatusUiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance) DeepCopyInto(out *Instance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance.
func (in *Instance) DeepCopy() *Instance {
	if in == nil {
		return nil
	}
	out := new(Instance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Instance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceList) DeepCopyInto(out *InstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Instance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceList.
func (in *InstanceList) DeepCopy() *InstanceList {
	if in == nil {
		return nil
	}
	out := new(InstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceRefFields) DeepCopyInto(out *InstanceRefFields) {
	*out = *in
	if in.Namespace != nil {
		in, out := &in.Namespace, &out.Namespace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceRefFields.
func (in *InstanceRefFields) DeepCopy() *InstanceRefFields {
	if in == nil {
		return nil
	}
	out := new(InstanceRefFields)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceReference) DeepCopyInto(out *InstanceReference) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]InstanceRefFields, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceReference.
func (in *InstanceReference) DeepCopy() *InstanceReference {
	if in == nil {
		return nil
	}
	out := new(InstanceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceSpec) DeepCopyInto(out *InstanceSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	in.GatusConfig.DeepCopyInto(&out.GatusConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceSpec.
func (in *InstanceSpec) DeepCopy() *InstanceSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceStatus) DeepCopyInto(out *InstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeploymentName != nil {
		in, out := &in.DeploymentName, &out.DeploymentName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceStatus.
func (in *InstanceStatus) DeepCopy() *InstanceStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConfig) DeepCopyInto(out *ServiceConfig) {
	*out = *in
	if in.ServiceAnnotations != nil {
		in, out := &in.ServiceAnnotations, &out.ServiceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ServiceLabels != nil {
		in, out := &in.ServiceLabels, &out.ServiceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IPFamilyPolicy != nil {
		in, out := &in.IPFamilyPolicy, &out.IPFamilyPolicy
		*out = new(corev1.IPFamilyPolicy)
		**out = **in
	}
	if in.IPFamilies != nil {
		in, out := &in.IPFamilies, &out.IPFamilies
		*out = make([]corev1.IPFamily, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConfig.
func (in *ServiceConfig) DeepCopy() *ServiceConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Suite) DeepCopyInto(out *Suite) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Suite.
func (in *Suite) DeepCopy() *Suite {
	if in == nil {
		return nil
	}
	out := new(Suite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Suite) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuiteConfigSpec) DeepCopyInto(out *SuiteConfigSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = make(map[string]runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]*SuiteEndpointSpec, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(SuiteEndpointSpec)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuiteConfigSpec.
func (in *SuiteConfigSpec) DeepCopy() *SuiteConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SuiteConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuiteEndpointSpec) DeepCopyInto(out *SuiteEndpointSpec) {
	*out = *in
	in.EndpointConfigSpec.DeepCopyInto(&out.EndpointConfigSpec)
	if in.AlwaysRun != nil {
		in, out := &in.AlwaysRun, &out.AlwaysRun
		*out = new(bool)
		**out = **in
	}
	if in.Store != nil {
		in, out := &in.Store, &out.Store
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuiteEndpointSpec.
func (in *SuiteEndpointSpec) DeepCopy() *SuiteEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(SuiteEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuiteList) DeepCopyInto(out *SuiteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Suite, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuiteList.
func (in *SuiteList) DeepCopy() *SuiteList {
	if in == nil {
		return nil
	}
	out := new(SuiteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SuiteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuiteSpec) DeepCopyInto(out *SuiteSpec) {
	*out = *in
	in.InstanceReference.DeepCopyInto(&out.InstanceReference)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuiteSpec.
func (in *SuiteSpec) DeepCopy() *SuiteSpec {
	if in == nil {
		return nil
	}
	out := new(SuiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SuiteStatus) DeepCopyInto(out *SuiteStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SuiteStatus.
func (in *SuiteStatus) DeepCopy() *SuiteStatus {
	if in == nil {
		return nil
	}
	out := new(SuiteStatus)
	in.DeepCopyInto(out)
	return out
}
