//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusAnnouncementConfig) DeepCopyInto(out *GatusAnnouncementConfig) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.Archived != nil {
		in, out := &in.Archived, &out.Archived
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusAnnouncementConfig.
func (in *GatusAnnouncementConfig) DeepCopy() *GatusAnnouncementConfig {
	if in == nil {
		return nil
	}
	out := new(GatusAnnouncementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusClientConfig) DeepCopyInto(out *GatusClientConfig) {
	*out = *in
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	if in.IgnoreRedirect != nil {
		in, out := &in.IgnoreRedirect, &out.IgnoreRedirect
		*out = new(bool)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.DNSResolver != nil {
		in, out := &in.DNSResolver, &out.DNSResolver
		*out = new(string)
		**out = **in
	}
	if in.Oauth2 != nil {
		in, out := &in.Oauth2, &out.Oauth2
		*out = new(GatusClientOauth2Config)
		(*in).DeepCopyInto(*out)
	}
	if in.ProxyURL != nil {
		in, out := &in.ProxyURL, &out.ProxyURL
		*out = new(string)
		**out = **in
	}
	if in.IdentityAwareProxy != nil {
		in, out := &in.IdentityAwareProxy, &out.IdentityAwareProxy
		*out = new(GatusClientIdentityAwareProxyConfig)
		**out = **in
	}
	if in.MTLS != nil {
		in, out := &in.MTLS, &out.MTLS
		*out = new(GatusClientmTLSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusClientConfig.
func (in *GatusClientConfig) DeepCopy() *GatusClientConfig {
	if in == nil {
		return nil
	}
	out := new(GatusClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusClientIdentityAwareProxyConfig) DeepCopyInto(out *GatusClientIdentityAwareProxyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusClientIdentityAwareProxyConfig.
func (in *GatusClientIdentityAwareProxyConfig) DeepCopy() *GatusClientIdentityAwareProxyConfig {
	if in == nil {
		return nil
	}
	out := new(GatusClientIdentityAwareProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusClientOauth2Config) DeepCopyInto(out *GatusClientOauth2Config) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusClientOauth2Config.
func (in *GatusClientOauth2Config) DeepCopy() *GatusClientOauth2Config {
	if in == nil {
		return nil
	}
	out := new(GatusClientOauth2Config)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusClientmTLSConfig) DeepCopyInto(out *GatusClientmTLSConfig) {
	*out = *in
	if in.CertificateFile != nil {
		in, out := &in.CertificateFile, &out.CertificateFile
		*out = new(string)
		**out = **in
	}
	if in.PrivateKeyFile != nil {
		in, out := &in.PrivateKeyFile, &out.PrivateKeyFile
		*out = new(string)
		**out = **in
	}
	if in.Renegotiation != nil {
		in, out := &in.Renegotiation, &out.Renegotiation
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusClientmTLSConfig.
func (in *GatusClientmTLSConfig) DeepCopy() *GatusClientmTLSConfig {
	if in == nil {
		return nil
	}
	out := new(GatusClientmTLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusConfig) DeepCopyInto(out *GatusConfig) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(bool)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(GatusStorageConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Alerting != nil {
		in, out := &in.Alerting, &out.Alerting
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Announcements != nil {
		in, out := &in.Announcements, &out.Announcements
		*out = make([]GatusAnnouncementConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]GatusEndpointConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExternalEndpoints != nil {
		in, out := &in.ExternalEndpoints, &out.ExternalEndpoints
		*out = make([]GatusExternalEndpointConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(GatusSecurityConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(int32)
		**out = **in
	}
	if in.SkipInvalidConfigUpdate != nil {
		in, out := &in.SkipInvalidConfigUpdate, &out.SkipInvalidConfigUpdate
		*out = new(bool)
		**out = **in
	}
	if in.Web != nil {
		in, out := &in.Web, &out.Web
		*out = new(GatusWebConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Ui != nil {
		in, out := &in.Ui, &out.Ui
		*out = new(GatusUiConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Maintenance != nil {
		in, out := &in.Maintenance, &out.Maintenance
		*out = new(GatusMaintenanceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Suites != nil {
		in, out := &in.Suites, &out.Suites
		*out = make([]GatusSuiteConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Connectivity != nil {
		in, out := &in.Connectivity, &out.Connectivity
		*out = new(GatusConnectivityConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusConfig.
func (in *GatusConfig) DeepCopy() *GatusConfig {
	if in == nil {
		return nil
	}
	out := new(GatusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusConnectivityCheckerConfig) DeepCopyInto(out *GatusConnectivityCheckerConfig) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusConnectivityCheckerConfig.
func (in *GatusConnectivityCheckerConfig) DeepCopy() *GatusConnectivityCheckerConfig {
	if in == nil {
		return nil
	}
	out := new(GatusConnectivityCheckerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusConnectivityConfig) DeepCopyInto(out *GatusConnectivityConfig) {
	*out = *in
	in.Checker.DeepCopyInto(&out.Checker)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusConnectivityConfig.
func (in *GatusConnectivityConfig) DeepCopy() *GatusConnectivityConfig {
	if in == nil {
		return nil
	}
	out := new(GatusConnectivityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusEndpointAlertConfig) DeepCopyInto(out *GatusEndpointAlertConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.FailureThreshold != nil {
		in, out := &in.FailureThreshold, &out.FailureThreshold
		*out = new(int32)
		**out = **in
	}
	if in.SuccessThreshold != nil {
		in, out := &in.SuccessThreshold, &out.SuccessThreshold
		*out = new(int32)
		**out = **in
	}
	if in.MinimumReminderInterval != nil {
		in, out := &in.MinimumReminderInterval, &out.MinimumReminderInterval
		*out = new(string)
		**out = **in
	}
	if in.SendOnResolved != nil {
		in, out := &in.SendOnResolved, &out.SendOnResolved
		*out = new(bool)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ProviderOverride != nil {
		in, out := &in.ProviderOverride, &out.ProviderOverride
		*out = make(map[string]runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusEndpointAlertConfig.
func (in *GatusEndpointAlertConfig) DeepCopy() *GatusEndpointAlertConfig {
	if in == nil {
		return nil
	}
	out := new(GatusEndpointAlertConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusEndpointConfig) DeepCopyInto(out *GatusEndpointConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
	if in.GraphQL != nil {
		in, out := &in.GraphQL, &out.GraphQL
		*out = new(bool)
		**out = **in
	}
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(string)
		**out = **in
	}
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(GatusEndpointDNSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SSH != nil {
		in, out := &in.SSH, &out.SSH
		*out = new(GatusEndpointSSHConfig)
		**out = **in
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]GatusEndpointAlertConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MaintenanceWindows != nil {
		in, out := &in.MaintenanceWindows, &out.MaintenanceWindows
		*out = make([]GatusMaintenanceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = new(GatusClientConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Ui != nil {
		in, out := &in.Ui, &out.Ui
		*out = new(GatusEndpointUiConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ExtraLabels != nil {
		in, out := &in.ExtraLabels, &out.ExtraLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AlwaysRun != nil {
		in, out := &in.AlwaysRun, &out.AlwaysRun
		*out = new(bool)
		**out = **in
	}
	if in.Store != nil {
		in, out := &in.Store, &out.Store
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusEndpointConfig.
func (in *GatusEndpointConfig) DeepCopy() *GatusEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(GatusEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusEndpointDNSConfig) DeepCopyInto(out *GatusEndpointDNSConfig) {
	*out = *in
	if in.QueryType != nil {
		in, out := &in.QueryType, &out.QueryType
		*out = new(string)
		**out = **in
	}
	if in.QueryName != nil {
		in, out := &in.QueryName, &out.QueryName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusEndpointDNSConfig.
func (in *GatusEndpointDNSConfig) DeepCopy() *GatusEndpointDNSConfig {
	if in == nil {
		return nil
	}
	out := new(GatusEndpointDNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusEndpointSSHConfig) DeepCopyInto(out *GatusEndpointSSHConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusEndpointSSHConfig.
func (in *GatusEndpointSSHConfig) DeepCopy() *GatusEndpointSSHConfig {
	if in == nil {
		return nil
	}
	out := new(GatusEndpointSSHConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusEndpointUiBadgeConfig) DeepCopyInto(out *GatusEndpointUiBadgeConfig) {
	*out = *in
	if in.ResponseTime != nil {
		in, out := &in.ResponseTime, &out.ResponseTime
		*out = new(GatusEndpointUiBadgeResponseTimeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusEndpointUiBadgeConfig.
func (in *GatusEndpointUiBadgeConfig) DeepCopy() *GatusEndpointUiBadgeConfig {
	if in == nil {
		return nil
	}
	out := new(GatusEndpointUiBadgeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusEndpointUiBadgeResponseTimeConfig) DeepCopyInto(out *GatusEndpointUiBadgeResponseTimeConfig) {
	*out = *in
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusEndpointUiBadgeResponseTimeConfig.
func (in *GatusEndpointUiBadgeResponseTimeConfig) DeepCopy() *GatusEndpointUiBadgeResponseTimeConfig {
	if in == nil {
		return nil
	}
	out := new(GatusEndpointUiBadgeResponseTimeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusEndpointUiConfig) DeepCopyInto(out *GatusEndpointUiConfig) {
	*out = *in
	if in.HideConditions != nil {
		in, out := &in.HideConditions, &out.HideConditions
		*out = new(bool)
		**out = **in
	}
	if in.HideHostname != nil {
		in, out := &in.HideHostname, &out.HideHostname
		*out = new(bool)
		**out = **in
	}
	if in.HidePort != nil {
		in, out := &in.HidePort, &out.HidePort
		*out = new(bool)
		**out = **in
	}
	if in.HideUrl != nil {
		in, out := &in.HideUrl, &out.HideUrl
		*out = new(bool)
		**out = **in
	}
	if in.HideErrors != nil {
		in, out := &in.HideErrors, &out.HideErrors
		*out = new(bool)
		**out = **in
	}
	if in.DontResolveFailedConditions != nil {
		in, out := &in.DontResolveFailedConditions, &out.DontResolveFailedConditions
		*out = new(bool)
		**out = **in
	}
	if in.ResolveSuccessfulConditions != nil {
		in, out := &in.ResolveSuccessfulConditions, &out.ResolveSuccessfulConditions
		*out = new(bool)
		**out = **in
	}
	if in.Badge != nil {
		in, out := &in.Badge, &out.Badge
		*out = new(GatusEndpointUiBadgeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusEndpointUiConfig.
func (in *GatusEndpointUiConfig) DeepCopy() *GatusEndpointUiConfig {
	if in == nil {
		return nil
	}
	out := new(GatusEndpointUiConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusExternalEndpointConfig) DeepCopyInto(out *GatusExternalEndpointConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	if in.Alerts != nil {
		in, out := &in.Alerts, &out.Alerts
		*out = make([]GatusEndpointAlertConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Heartbeat.DeepCopyInto(&out.Heartbeat)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusExternalEndpointConfig.
func (in *GatusExternalEndpointConfig) DeepCopy() *GatusExternalEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(GatusExternalEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusExternalEndpointHeartbeatConfig) DeepCopyInto(out *GatusExternalEndpointHeartbeatConfig) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusExternalEndpointHeartbeatConfig.
func (in *GatusExternalEndpointHeartbeatConfig) DeepCopy() *GatusExternalEndpointHeartbeatConfig {
	if in == nil {
		return nil
	}
	out := new(GatusExternalEndpointHeartbeatConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusInstanceConfig) DeepCopyInto(out *GatusInstanceConfig) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(bool)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(GatusStorageConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Alerting != nil {
		in, out := &in.Alerting, &out.Alerting
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(GatusSecurityConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Concurrency != nil {
		in, out := &in.Concurrency, &out.Concurrency
		*out = new(int32)
		**out = **in
	}
	if in.Web != nil {
		in, out := &in.Web, &out.Web
		*out = new(GatusInstanceWebConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Ui != nil {
		in, out := &in.Ui, &out.Ui
		*out = new(GatusUiConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Maintenance != nil {
		in, out := &in.Maintenance, &out.Maintenance
		*out = new(GatusMaintenanceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Connectivity != nil {
		in, out := &in.Connectivity, &out.Connectivity
		*out = new(GatusConnectivityConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusInstanceConfig.
func (in *GatusInstanceConfig) DeepCopy() *GatusInstanceConfig {
	if in == nil {
		return nil
	}
	out := new(GatusInstanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusInstanceWebConfig) DeepCopyInto(out *GatusInstanceWebConfig) {
	*out = *in
	if in.ReadBufferSize != nil {
		in, out := &in.ReadBufferSize, &out.ReadBufferSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusInstanceWebConfig.
func (in *GatusInstanceWebConfig) DeepCopy() *GatusInstanceWebConfig {
	if in == nil {
		return nil
	}
	out := new(GatusInstanceWebConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusMaintenanceConfig) DeepCopyInto(out *GatusMaintenanceConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Timezone != nil {
		in, out := &in.Timezone, &out.Timezone
		*out = new(string)
		**out = **in
	}
	if in.Every != nil {
		in, out := &in.Every, &out.Every
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusMaintenanceConfig.
func (in *GatusMaintenanceConfig) DeepCopy() *GatusMaintenanceConfig {
	if in == nil {
		return nil
	}
	out := new(GatusMaintenanceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusSecurityBasicConfig) DeepCopyInto(out *GatusSecurityBasicConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusSecurityBasicConfig.
func (in *GatusSecurityBasicConfig) DeepCopy() *GatusSecurityBasicConfig {
	if in == nil {
		return nil
	}
	out := new(GatusSecurityBasicConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusSecurityConfig) DeepCopyInto(out *GatusSecurityConfig) {
	*out = *in
	if in.Basic != nil {
		in, out := &in.Basic, &out.Basic
		*out = new(GatusSecurityBasicConfig)
		**out = **in
	}
	if in.OIDC != nil {
		in, out := &in.OIDC, &out.OIDC
		*out = new(GatusSecurityOIDCConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusSecurityConfig.
func (in *GatusSecurityConfig) DeepCopy() *GatusSecurityConfig {
	if in == nil {
		return nil
	}
	out := new(GatusSecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusSecurityOIDCConfig) DeepCopyInto(out *GatusSecurityOIDCConfig) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedSubjects != nil {
		in, out := &in.AllowedSubjects, &out.AllowedSubjects
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SessionTTL != nil {
		in, out := &in.SessionTTL, &out.SessionTTL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusSecurityOIDCConfig.
func (in *GatusSecurityOIDCConfig) DeepCopy() *GatusSecurityOIDCConfig {
	if in == nil {
		return nil
	}
	out := new(GatusSecurityOIDCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusStorageConfig) DeepCopyInto(out *GatusStorageConfig) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(GatusStorageType)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Caching != nil {
		in, out := &in.Caching, &out.Caching
		*out = new(bool)
		**out = **in
	}
	if in.MaximumResultsNum != nil {
		in, out := &in.MaximumResultsNum, &out.MaximumResultsNum
		*out = new(int32)
		**out = **in
	}
	if in.MaximumEventsNum != nil {
		in, out := &in.MaximumEventsNum, &out.MaximumEventsNum
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusStorageConfig.
func (in *GatusStorageConfig) DeepCopy() *GatusStorageConfig {
	if in == nil {
		return nil
	}
	out := new(GatusStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusSuiteConfig) DeepCopyInto(out *GatusSuiteConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(string)
		**out = **in
	}
	if in.Context != nil {
		in, out := &in.Context, &out.Context
		*out = make(map[string]runtime.RawExtension, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]GatusEndpointConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusSuiteConfig.
func (in *GatusSuiteConfig) DeepCopy() *GatusSuiteConfig {
	if in == nil {
		return nil
	}
	out := new(GatusSuiteConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusUiButtonConfig) DeepCopyInto(out *GatusUiButtonConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusUiButtonConfig.
func (in *GatusUiButtonConfig) DeepCopy() *GatusUiButtonConfig {
	if in == nil {
		return nil
	}
	out := new(GatusUiButtonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusUiConfig) DeepCopyInto(out *GatusUiConfig) {
	*out = *in
	if in.Title != nil {
		in, out := &in.Title, &out.Title
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DashboardHeading != nil {
		in, out := &in.DashboardHeading, &out.DashboardHeading
		*out = new(string)
		**out = **in
	}
	if in.DashboardSubheading != nil {
		in, out := &in.DashboardSubheading, &out.DashboardSubheading
		*out = new(string)
		**out = **in
	}
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(string)
		**out = **in
	}
	if in.Logo != nil {
		in, out := &in.Logo, &out.Logo
		*out = new(string)
		**out = **in
	}
	if in.Link != nil {
		in, out := &in.Link, &out.Link
		*out = new(string)
		**out = **in
	}
	if in.Buttons != nil {
		in, out := &in.Buttons, &out.Buttons
		*out = make([]GatusUiButtonConfig, len(*in))
		copy(*out, *in)
	}
	if in.CustomCSS != nil {
		in, out := &in.CustomCSS, &out.CustomCSS
		*out = new(string)
		**out = **in
	}
	if in.Darkmode != nil {
		in, out := &in.Darkmode, &out.Darkmode
		*out = new(bool)
		**out = **in
	}
	if in.DefaultSortBy != nil {
		in, out := &in.DefaultSortBy, &out.DefaultSortBy
		*out = new(string)
		**out = **in
	}
	if in.DefaultFilterBy != nil {
		in, out := &in.DefaultFilterBy, &out.DefaultFilterBy
		*out = new(string)
		**out = **in
	}
	if in.LoginSubtitle != nil {
		in, out := &in.LoginSubtitle, &out.LoginSubtitle
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusUiConfig.
func (in *GatusUiConfig) DeepCopy() *GatusUiConfig {
	if in == nil {
		return nil
	}
	out := new(GatusUiConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusUiFaviconConfig) DeepCopyInto(out *GatusUiFaviconConfig) {
	*out = *in
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(string)
		**out = **in
	}
	if in.Size16x16 != nil {
		in, out := &in.Size16x16, &out.Size16x16
		*out = new(string)
		**out = **in
	}
	if in.Size32x32 != nil {
		in, out := &in.Size32x32, &out.Size32x32
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusUiFaviconConfig.
func (in *GatusUiFaviconConfig) DeepCopy() *GatusUiFaviconConfig {
	if in == nil {
		return nil
	}
	out := new(GatusUiFaviconConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatusWebConfig) DeepCopyInto(out *GatusWebConfig) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
	if in.ReadBufferSize != nil {
		in, out := &in.ReadBufferSize, &out.ReadBufferSize
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatusWebConfig.
func (in *GatusWebConfig) DeepCopy() *GatusWebConfig {
	if in == nil {
		return nil
	}
	out := new(GatusWebConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance) DeepCopyInto(out *Instance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance.
func (in *Instance) DeepCopy() *Instance {
	if in == nil {
		return nil
	}
	out := new(Instance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Instance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceList) DeepCopyInto(out *InstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Instance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceList.
func (in *InstanceList) DeepCopy() *InstanceList {
	if in == nil {
		return nil
	}
	out := new(InstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceSpec) DeepCopyInto(out *InstanceSpec) {
	*out = *in
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Image != nil {
		in, out := &in.Image, &out.Image
		*out = new(string)
		**out = **in
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	in.GatusConfig.DeepCopyInto(&out.GatusConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceSpec.
func (in *InstanceSpec) DeepCopy() *InstanceSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceStatus) DeepCopyInto(out *InstanceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeploymentName != nil {
		in, out := &in.DeploymentName, &out.DeploymentName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceStatus.
func (in *InstanceStatus) DeepCopy() *InstanceStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConfig) DeepCopyInto(out *ServiceConfig) {
	*out = *in
	if in.ServiceAnnotations != nil {
		in, out := &in.ServiceAnnotations, &out.ServiceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ServiceLabels != nil {
		in, out := &in.ServiceLabels, &out.ServiceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IPFamilyPolicy != nil {
		in, out := &in.IPFamilyPolicy, &out.IPFamilyPolicy
		*out = new(corev1.IPFamilyPolicy)
		**out = **in
	}
	if in.IPFamilies != nil {
		in, out := &in.IPFamilies, &out.IPFamilies
		*out = make([]corev1.IPFamily, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConfig.
func (in *ServiceConfig) DeepCopy() *ServiceConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceConfig)
	in.DeepCopyInto(out)
	return out
}
